#!/bin/bash

echo "Reddit MCP Server Deployment Guide"
echo "=================================="
echo ""
echo "Choose your deployment platform:"
echo ""
echo "1. Railway (Recommended - Free tier available)"
echo "   - Visit: https://railway.app"
echo "   - Connect GitHub repo"
echo "   - Deploy automatically"
echo "   - Gets URL like: https://reddit-mcp-server-production.up.railway.app"
echo ""
echo "2. Render (Free tier available)"
echo "   - Visit: https://render.com"
echo "   - Connect GitHub repo"
echo "   - Use render.yaml config"
echo "   - Gets URL like: https://reddit-mcp-server.onrender.com"
echo ""
echo "3. Heroku (Free tier discontinued, paid plans available)"
echo "   - Install Heroku CLI"
echo "   - heroku create your-app-name"
echo "   - git push heroku main"
echo "   - Gets URL like: https://your-app-name.herokuapp.com"
echo ""
echo "4. DigitalOcean App Platform"
echo "   - Visit: https://cloud.digitalocean.com/apps"
echo "   - Connect GitHub repo"
echo "   - $5/month minimum"
echo ""
echo "Your MCP Server URL will be: https://your-domain.com/mcp"
echo "Manifest URL will be: https://your-domain.com/mcp/manifest.json"