services:
  - type: web
    name: reddit-mcp-server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT reddit_mcp_server:app
    healthCheckPath: /mcp/manifest.json
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0